# Generated by Django 2.2.1 on 2020-05-01 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uye',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AddField(
            model_name='uye',
            name='kayitTarihi',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Kayıt Tarihi'),
        ),
    ]
