# Generated by Django 2.2.1 on 2020-05-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200501_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uye',
            name='ad',
            field=models.TextField(max_length=30, verbose_name='Ad label'),
        ),
        migrations.AlterField(
            model_name='uye',
            name='soyad',
            field=models.TextField(max_length=30, verbose_name='Soyad label'),
        ),
    ]
