# Generated by Django 2.2.1 on 2020-05-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200501_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='uye',
            name='UyeKodu',
            field=models.CharField(default='28383715', max_length=8, verbose_name='Üye Kodu'),
        ),
        migrations.AlterField(
            model_name='uye',
            name='ad',
            field=models.TextField(max_length=30, verbose_name='Ad '),
        ),
        migrations.AlterField(
            model_name='uye',
            name='soyad',
            field=models.TextField(max_length=30, verbose_name='Soyad '),
        ),
    ]
