# Generated by Django 2.2.1 on 2020-05-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200502_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uye',
            name='UyeKodu',
            field=models.CharField(default='85940809', max_length=8, verbose_name='Üye Kodu'),
        ),
    ]
