# Generated by Django 2.2.1 on 2020-05-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200502_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uye',
            name='UyeKodu',
            field=models.CharField(default='64353205', max_length=8, verbose_name='Üye Kodu'),
        ),
    ]
