# Generated by Django 2.2.1 on 2020-05-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200502_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uye',
            name='UyeKodu',
            field=models.CharField(default='59666097', max_length=8, verbose_name='Üye Kodu'),
        ),
    ]
