# Generated by Django 2.2.1 on 2020-05-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200502_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uye',
            name='UyeKodu',
            field=models.CharField(default='28024720', max_length=8, verbose_name='Üye Kodu'),
        ),
        migrations.AlterField(
            model_name='uye',
            name='ad',
            field=models.CharField(max_length=30, verbose_name='Ad '),
        ),
        migrations.AlterField(
            model_name='uye',
            name='soyad',
            field=models.CharField(max_length=30, verbose_name='Soyad '),
        ),
    ]
