# Generated by Django 2.2.1 on 2020-05-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200509_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uye',
            name='UyeKodu',
            field=models.CharField(default='41740969', max_length=8, verbose_name='Üye Kodu'),
        ),
    ]
