# Generated by Django 2.2.1 on 2020-05-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200525_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uye',
            name='UyeKodu',
            field=models.CharField(default='15046822', max_length=8, verbose_name='Üye Kodu'),
        ),
    ]
