# Generated by Django 2.2.1 on 2020-05-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200525_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uye',
            name='kayitTarihi',
        ),
        migrations.AlterField(
            model_name='uye',
            name='UyeKodu',
            field=models.CharField(default='44569589', max_length=8, verbose_name='Üye Kodu'),
        ),
    ]
