# Generated by Django 2.2.1 on 2020-05-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200525_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uye',
            name='UyeKodu',
            field=models.CharField(default='11572389', max_length=8, verbose_name='Üye Kodu'),
        ),
    ]
