# Generated by Django 2.2.1 on 2020-05-25 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200525_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='uye',
            name='kayitTarihi',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Kayıt Tarihi'),
        ),
        migrations.AlterField(
            model_name='uye',
            name='UyeKodu',
            field=models.CharField(default='51699037', max_length=8, verbose_name='Üye Kodu'),
        ),
    ]
