# Generated by Django 2.2.1 on 2020-05-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtikTemel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AtikKodu', models.CharField(max_length=40, verbose_name='Atık Kodu')),
                ('FizikselOzellik', models.TextField(verbose_name='Fiziksel Özellikleri')),
                ('Renk', models.TextField(verbose_name='Renk')),
                ('TehlikeOzellik', models.TextField(verbose_name='Tehlike Özellikleri')),
                ('ProsesBilgi', models.TextField(verbose_name='Proses Bilgileri')),
                ('AtikAnaliz', models.TextField(verbose_name='Atık Analizleri')),
                ('Miktar', models.CharField(max_length=400, verbose_name='Yıllık Atık Miktarı')),
                ('TasimaOnlem', models.TextField(verbose_name='Taşıma Önlemleri')),
                ('Notlar', models.TextField(verbose_name='Notlar')),
                ('Dosyalar', models.FileField(upload_to='', verbose_name='Dosyalar')),
            ],
            options={
                'verbose_name': 'Atık',
                'verbose_name_plural': 'Atıklar',
            },
        ),
    ]
