# Generated by Django 2.2.1 on 2020-05-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atiktemel',
            name='AtikAnaliz',
            field=models.TextField(blank=True, verbose_name='Atık Analizleri'),
        ),
        migrations.AlterField(
            model_name='atiktemel',
            name='Dosyalar',
            field=models.FileField(blank=True, upload_to='', verbose_name='Dosyalar'),
        ),
        migrations.AlterField(
            model_name='atiktemel',
            name='Notlar',
            field=models.TextField(blank=True, verbose_name='Notlar'),
        ),
        migrations.AlterField(
            model_name='atiktemel',
            name='ProsesBilgi',
            field=models.TextField(blank=True, verbose_name='Proses Bilgileri'),
        ),
        migrations.AlterField(
            model_name='atiktemel',
            name='Renk',
            field=models.TextField(blank=True, verbose_name='Renk'),
        ),
        migrations.AlterField(
            model_name='atiktemel',
            name='TasimaOnlem',
            field=models.TextField(blank=True, verbose_name='Taşıma Önlemleri'),
        ),
        migrations.AlterField(
            model_name='atiktemel',
            name='TehlikeOzellik',
            field=models.TextField(blank=True, verbose_name='Tehlike Özellikleri'),
        ),
    ]
