# Generated by Django 2.2.1 on 2020-05-02 11:05

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200502_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='UreticiBilgileri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirmaUnvani', models.TextField(verbose_name='Firma Ünvanı')),
                ('NACE', models.CharField(max_length=8, verbose_name='NACE Kodu')),
                ('FaaliyetAlani', models.TextField(verbose_name='Faaliyet Alanı')),
                ('Adres', models.CharField(max_length=300, verbose_name='Firma Adresi')),
                ('Il', models.TextField(verbose_name='İl')),
                ('Ilce', models.TextField(verbose_name='İlçe')),
                ('FirmaTel', models.IntegerField(max_length=11, verbose_name='Firma Tel')),
                ('Email', models.EmailField(max_length=254, verbose_name='Firma Email')),
                ('WebSitesi', models.CharField(max_length=100, verbose_name='Firma Web Sitesi')),
                ('IlgiliAd', models.TextField(verbose_name='İlgili Kişi Adı')),
                ('IlgiliTel', models.IntegerField(verbose_name='İlgili Kişi Tel')),
                ('IlgiliEmail', models.EmailField(max_length=254, verbose_name='İlgili Kişi Email')),
                ('Konum', location_field.models.plain.PlainLocationField(max_length=63)),
            ],
        ),
    ]
