# Generated by Django 2.2.1 on 2020-05-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ureticibilgileri'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ureticibilgileri',
            options={'verbose_name': 'Üretici Bilgileri', 'verbose_name_plural': 'Üreticiler'},
        ),
        migrations.AlterField(
            model_name='ureticibilgileri',
            name='Adres',
            field=models.CharField(blank=True, max_length=300, verbose_name='Firma Adresi'),
        ),
        migrations.AlterField(
            model_name='ureticibilgileri',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Firma Email'),
        ),
        migrations.AlterField(
            model_name='ureticibilgileri',
            name='FaaliyetAlani',
            field=models.TextField(blank=True, verbose_name='Faaliyet Alanı'),
        ),
        migrations.AlterField(
            model_name='ureticibilgileri',
            name='FirmaTel',
            field=models.IntegerField(blank=True, max_length=11, verbose_name='Firma Tel'),
        ),
        migrations.AlterField(
            model_name='ureticibilgileri',
            name='Ilce',
            field=models.TextField(blank=True, verbose_name='İlçe'),
        ),
        migrations.AlterField(
            model_name='ureticibilgileri',
            name='IlgiliAd',
            field=models.TextField(blank=True, verbose_name='İlgili Kişi Adı'),
        ),
        migrations.AlterField(
            model_name='ureticibilgileri',
            name='IlgiliEmail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='İlgili Kişi Email'),
        ),
        migrations.AlterField(
            model_name='ureticibilgileri',
            name='IlgiliTel',
            field=models.IntegerField(blank=True, verbose_name='İlgili Kişi Tel'),
        ),
        migrations.AlterField(
            model_name='ureticibilgileri',
            name='WebSitesi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Firma Web Sitesi'),
        ),
    ]
