# Generated by Django 2.2.1 on 2020-05-09 13:51

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200502_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmaBilgileri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Durum', models.BooleanField(verbose_name='Durum')),
                ('FirmaUnvani', models.CharField(max_length=50, verbose_name='Firma Ünvanı')),
                ('NACE', models.CharField(max_length=8, verbose_name='NACE Kodu')),
                ('FaaliyetAlani', models.TextField(blank=True, verbose_name='Faaliyet Alanı')),
                ('Adres', models.CharField(blank=True, max_length=300, verbose_name='Firma Adresi')),
                ('Il', models.CharField(max_length=30, verbose_name='İl')),
                ('Ilce', models.CharField(blank=True, max_length=30, verbose_name='İlçe')),
                ('FirmaTel', models.IntegerField(blank=True, verbose_name='Firma Tel')),
                ('Email', models.EmailField(blank=True, max_length=254, verbose_name='Firma Email')),
                ('WebSitesi', models.CharField(blank=True, max_length=100, verbose_name='Firma Web Sitesi')),
                ('IlgiliAd', models.CharField(blank=True, max_length=50, verbose_name='İlgili Kişi Adı')),
                ('IlgiliTel', models.IntegerField(blank=True, verbose_name='İlgili Kişi Tel')),
                ('IlgiliEmail', models.EmailField(blank=True, max_length=254, verbose_name='İlgili Kişi Email')),
                ('Konum', location_field.models.plain.PlainLocationField(max_length=63)),
            ],
            options={
                'verbose_name': 'Firma Bilgileri',
                'verbose_name_plural': 'Firmalar',
            },
        ),
        migrations.DeleteModel(
            name='UreticiBilgileri',
        ),
        migrations.AlterField(
            model_name='atiktemel',
            name='Renk',
            field=models.CharField(blank=True, max_length=20, verbose_name='Renk'),
        ),
        migrations.AddField(
            model_name='firmabilgileri',
            name='Atiklar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AtikTemel'),
        ),
    ]
