# Generated by Django 2.2.1 on 2020-05-25 17:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200525_2000'),
        ('main', '0005_auto_20200509_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmabilgileri',
            name='Atiklar',
        ),
        migrations.AddField(
            model_name='atiktemel',
            name='firma',
            field=models.ForeignKey(default=datetime.datetime(2020, 5, 25, 17, 0, 29, 846714, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='main.FirmaBilgileri'),
        ),
        migrations.AddField(
            model_name='firmabilgileri',
            name='UyeKodu',
            field=models.ForeignKey(default=datetime.datetime(2020, 5, 25, 17, 0, 29, 845716, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='account.Uye'),
        ),
        migrations.CreateModel(
            name='BilesenAnaliz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AtikTanim', models.TextField(verbose_name='Atık Tanımı')),
                ('TicariAdi', models.CharField(max_length=40, verbose_name='Atığın Ticari Adı')),
                ('Synonim1', models.CharField(max_length=40, verbose_name='Sinonim1')),
                ('Synonim2', models.CharField(max_length=40, verbose_name='Sinonim2')),
                ('ProsesAmac', models.TextField(verbose_name='Prosesin Amacı')),
                ('ProsesAsama', models.CharField(max_length=50, verbose_name='Atığın Kaynaklandığı Proses Aşaması')),
                ('ProsesOzet', models.TextField(verbose_name='Proses Özeti')),
                ('EK3B', models.FileField(upload_to='', verbose_name='Ek3-B Analizi')),
                ('EK2', models.FileField(upload_to='', verbose_name='EK-2 Analizi')),
                ('AtikKodu', models.ForeignKey(default=datetime.datetime(2020, 5, 25, 17, 0, 29, 847710, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='main.AtikTemel')),
            ],
            options={
                'verbose_name': 'Bilesen',
                'verbose_name_plural': 'Bilesenler',
            },
        ),
    ]
