# Generated by Django 2.2.1 on 2020-05-25 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200525_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atiktemel',
            name='firma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.FirmaBilgileri'),
        ),
        migrations.AlterField(
            model_name='bilesenanaliz',
            name='AtikKodu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AtikTemel'),
        ),
        migrations.AlterField(
            model_name='firmabilgileri',
            name='UyeKodu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Uye'),
        ),
    ]
