# Generated by Django 2.2.1 on 2020-05-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200525_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atiktemel',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='bilesenanaliz',
            name='AtikKodu',
        ),
        migrations.RemoveField(
            model_name='firmabilgileri',
            name='UyeKodu',
        ),
    ]
